---
- name: Add resource pool to vCenter
  vmware_resource_pool:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.admin_user }}"
    password: "{{ vcenter.admin_pass }}"
    datacenter: "{{ vcenter.datacenter }}"
    cluster: "{{ vcenter.cluster }}"
    resource_pool: "{{ item }}"
    validate_certs: "{{ validate_certs }}"
    state: present
  delegate_to: localhost
  with_items: "{{ vcenter.resource_pools }}"
  run_once: true
  tags:
    - create_resource_pool
