---
- name: Create a VM folder on given datacenter
  vcenter_folder:
    hostname: "{{ ansible_host }}"
    username: "{{ vcenter.admin_user }}"
    password: "{{ vcenter.admin_pass }}"
    datacenter_name: "{{ item.0.name }}"
    folder_name: "{{ item.1 }}"
    folder_type: vm
    state: present
    validate_certs: "{{ validate_certs }}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"
  with_subelements:
    - "{{ vcenter.datacenters }}"
    - folders
  tags:
    - create_folder
